<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.codzs</groupId>
	<artifactId>java-codzs-framework</artifactId>
	<version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>java-codzs-framework</name>
	<description>Framework code for Java</description>

	<properties>
		<java.version>17</java.version>
		<maven.compiler.source>19</maven.compiler.source>
		<maven.compiler.target>19</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<codzs-framework-version>0.0.1-SNAPSHOT</codzs-framework-version>
		<spring-boot-version>3.1.1-SNAPSHOT</spring-boot-version>
		<spring-boot-starter-parent-version>3.1.0</spring-boot-starter-parent-version>
		<spring-cloud.version>2022.0.3</spring-cloud.version>
		<spring-boot-admin.version>3.0.4</spring-boot-admin.version>
		<spring-cloud-build-tools-version>4.0.3</spring-cloud-build-tools-version>

		<commons-langs-version>3.12.0</commons-langs-version>
		<freemarker-version>2.3.31</freemarker-version>
		<jackson-databind-version>2.14.2</jackson-databind-version>
		<openapi-version>2.1.0</openapi-version>
		<therapi-runtime-javadoc-version>0.15.0</therapi-runtime-javadoc-version>
		<mysql-connector-java-version>8.0.27</mysql-connector-java-version>
		<flyway-version>9.20.0</flyway-version>
		<logback-json-classic-version>0.1.5</logback-json-classic-version>
		<mapstruct-version>1.5.5.Final</mapstruct-version>
		<lombok.version>1.18.22</lombok.version>
		<lombok-mapstruct-binding-version>0.2.0</lombok-mapstruct-binding-version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-lang3</artifactId>
				<version>${commons-langs-version}</version>
			</dependency>
			<dependency>
				<groupId>org.freemarker</groupId>
				<artifactId>freemarker</artifactId>
				<version>${freemarker-version}</version>
			</dependency>
			<dependency>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-databind</artifactId>
				<version>${jackson-databind-version}</version>
			</dependency>

			<dependency>
				<groupId>de.codecentric</groupId>
				<artifactId>spring-boot-admin-starter-client</artifactId>
				<version>${spring-boot-admin.version}</version>
			</dependency>

			<!-- Start| Spring Build Tools: Dependencies -->
			<dependency>
				<groupId>org.springdoc</groupId>
				<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
				<version>${openapi-version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.therapi</groupId>
				<artifactId>therapi-runtime-javadoc</artifactId>
				<version>${therapi-runtime-javadoc-version}</version>
			</dependency>
			<!-- End| Spring Build Tools: Dependencies -->

			<!-- Start| dependency for mysql -->
			<dependency>
				<groupId>mysql</groupId>
				<artifactId>mysql-connector-java</artifactId>
				<scope>runtime</scope>
				<version>${mysql-connector-java-version}</version>
			</dependency>
			<dependency>
				<groupId>org.flywaydb</groupId>
				<artifactId>flyway-mysql</artifactId>
				<version>${flyway-version}</version>
			</dependency>

			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-parent</artifactId>
				<version>${spring-boot-starter-parent-version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>de.codecentric</groupId>
				<artifactId>spring-boot-admin-dependencies</artifactId>
				<version>${spring-boot-admin.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<dependency>
				<groupId>ch.qos.logback.contrib</groupId>
				<artifactId>logback-json-classic</artifactId>
				<version>${logback-json-classic-version}</version>
			</dependency>

			<dependency>
				<groupId>org.mapstruct</groupId>
				<artifactId>mapstruct</artifactId>
				<version>${mapstruct-version}</version>
			</dependency>
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
			</dependency>
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok-mapstruct-binding</artifactId>
				<version>${lombok-mapstruct-binding-version}</version>
			</dependency>

			<dependency>
				<groupId>ch.qos.logback.contrib</groupId>
				<artifactId>logback-jackson</artifactId>
				<version>${logback-json-classic-version}</version>
			</dependency>

			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-build-tools</artifactId>
				<version>${spring-cloud-build-tools-version}</version>
			</dependency>

			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-test</artifactId>
				<version>${spring-boot-version}</version>
			</dependency>

			<dependency>
				<groupId>com.codzs</groupId>
				<artifactId>utility</artifactId>
				<version>${codzs-framework-version}</version>
			</dependency>

			<dependency>
				<groupId>com.codzs</groupId>
				<artifactId>admin-client-service</artifactId>
				<version>${codzs-framework-version}</version>
			</dependency>

			<dependency>
				<groupId>com.codzs</groupId>
				<artifactId>config-client-service</artifactId>
				<version>${codzs-framework-version}</version>
			</dependency>

			<dependency>
				<groupId>com.codzs</groupId>
				<artifactId>resource-service</artifactId>
				<version>${codzs-framework-version}</version>
			</dependency>
			<dependency>
				<groupId>com.codzs</groupId>
				<artifactId>auth-user-detail-service</artifactId>
				<version>${codzs-framework-version}</version>
			</dependency>
			<dependency>
				<groupId>com.codzs</groupId>
				<artifactId>redis-cache</artifactId>
				<version>${codzs-framework-version}</version>
			</dependency>
			<dependency>
				<groupId>com.codzs</groupId>
				<artifactId>core</artifactId>
				<version>${codzs-framework-version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>${spring-boot-version}</version>
			</plugin>
			<plugin>
				<groupId>org.flywaydb</groupId>
				<artifactId>flyway-maven-plugin</artifactId>
				<version>${flyway-version}</version>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<releases>
				<enabled>false</enabled>
			</releases>
		</repository>
		<repository>
			<id>centralhttps</id>
			<name>Maven central https</name>
			<url>https://repo1.maven.org/maven2/</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
		<pluginRepository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<releases>
				<enabled>false</enabled>
			</releases>
		</pluginRepository>
		<pluginRepository>
			<id>centralhttps</id>
			<name>Maven central https</name>
			<url>https://repo1.maven.org/maven2/</url>
			<releases>
				<enabled>false</enabled>
			</releases>
		</pluginRepository>
	</pluginRepositories>

	<distributionManagement>
		<snapshotRepository>
			<id>nexus-snapshots</id>
			<url>http://localhost:8081/repository/maven-snapshots/</url>
		</snapshotRepository>
		<repository>
			<id>nexus-release</id>
			<url>http://localhost:8081/repository/maven-releases/</url>
		</repository>
	</distributionManagement>

	<modules>
		<module>utility</module>
		<module>resource-service</module>
		<module>admin-client-service</module>
		<module>config-client-service</module>
		<module>auth-client-service</module>
		<module>auth-client-service/auth-user-detail-service</module>
		<module>cache</module>
		<module>core</module>
        <module>jdbc-support</module>
    </modules>
</project>
